# Testing 
name: CI/CD to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker to Google Cloud
      run: |
        gcloud auth configure-docker africa-south1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        cd back_end
        docker build -t africa-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hms-docker/hms-docker-image:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push africa-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hms-docker/hms-docker-image:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy hms-docker-image \
          --image africa-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hms-docker/hms-docker-image:${{ github.sha }} \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
